# Generated by Django 2.2.6 on 2019-11-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
