# Generated by Django 2.2.6 on 2019-12-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_auto_20191128_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
