# Generated by Django 2.2.6 on 2019-12-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_auto_20191201_2052"),
    ]

    operations = [
        migrations.RenameField(model_name="order", old_name="item", new_name="wish",),
    ]
