# Generated by Django 2.2.8 on 2019-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_auto_20191209_0839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
