# Generated by Django 2.2.8 on 2019-12-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_auto_20191211_1826"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="unit_price",),
        migrations.RemoveField(model_name="product", name="url",),
        migrations.RemoveField(model_name="product", name="vendor",),
    ]
