# Generated by Django 2.2.9 on 2020-01-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_auto_20200113_1923"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("request_order", "Can request a order"),
                    ("approve_order", "Can approve a order"),
                    ("receive_order", "Can receive order"),
                    ("complete_order", "Can complete order"),
                    ("export_csv", "Can export all orders as CSV"),
                    ("view_order_all_teams", "Can view orders for all teams"),
                    ("add_order_all_teams", "Can add orders for all teams"),
                    ("change_order_all_teams", "Can change orders for all teams"),
                    ("delete_order_all_teams", "Can delete orders for all teams"),
                ]
            },
        ),
    ]
