# Generated by Django 2.2.9 on 2020-01-31 19:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_auto_20200131_1610"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_net",
                    models.BooleanField(
                        default=True, verbose_name="Is this purchase_net net sum?"
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, verbose_name="Is the purchase_net paid?"
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=255)),
                (
                    "payer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Person who paid the invoice",
                    ),
                ),
                ("ordered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.Vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit_price",
                    models.PositiveIntegerField(
                        verbose_name="Unit price in 100th cent"
                    ),
                ),
                ("unit", models.CharField(default="Stück", max_length=20)),
                (
                    "tax_rate",
                    models.PositiveIntegerField(
                        default=19, verbose_name="Tax rate in %"
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods",
                        to="orders.Purchase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="good",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.Good",
            ),
        ),
    ]
