default_stages: [commit]
repos:
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.1.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: flake8
    -   id: requirements-txt-fixer