# Generated by Django 3.0.7 on 2020-06-20 00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("orders", "0001_initial"),
        ("orders", "0002_auto_20191124_2004"),
        ("orders", "0003_order_state"),
        ("orders", "0004_order_unit_price"),
        ("orders", "0005_auto_20191124_2145"),
        ("orders", "0006_auto_20191125_1325"),
        ("orders", "0007_product_unit_price"),
        ("orders", "0008_auto_20191128_2013"),
        ("orders", "0009_auto_20191201_2035"),
        ("orders", "0010_auto_20191201_2052"),
        ("orders", "0011_auto_20191201_2055"),
        ("orders", "0012_auto_20191202_2113"),
        ("orders", "0013_auto_20191203_2327"),
        ("orders", "0014_auto_20191206_0926"),
        ("orders", "0015_auto_20191208_1753"),
        ("orders", "0016_auto_20191208_1859"),
        ("orders", "0017_auto_20191208_2048"),
        ("orders", "0018_auto_20191209_0839"),
        ("orders", "0019_auto_20191211_1826"),
        ("orders", "0020_auto_20191219_2037"),
        ("orders", "0021_order_comment"),
        ("orders", "0022_auto_20200112_1611"),
        ("orders", "0023_auto_20200113_1923"),
        ("orders", "0024_auto_20200131_1416"),
        ("orders", "0025_auto_20200131_1610"),
        ("orders", "0026_auto_20200131_1936"),
        ("orders", "0027_auto_20200413_1459"),
        ("orders", "0028_auto_20200421_1957"),
        ("orders", "0029_remove_product_sugesstion"),
        ("orders", "0030_require_product"),
        ("orders", "0031_product_pk_to_name"),
        ("orders", "0032_remove_url"),
        ("orders", "0033_remove_good"),
        ("orders", "0034_unit_price_allow_empty"),
        ("orders", "0035_product_unit_not_required"),
        ("orders", "0036_product_default_price"),
        ("orders", "0037_order_event_required"),
        ("orders", "0038_pillage_stockpile"),
        ("orders", "0039_remove_order_unit_price"),
        ("orders", "0040_auto_20200424_1740"),
        ("orders", "0041_product_unit_allow_empty"),
        ("orders", "0042_auto_20200614_1936"),
        ("orders", "0043_auto_20200614_2214"),
        ("orders", "0044_auto_20200616_2138"),
        ("orders", "0045_auto_20200616_2328"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50, unique=True)),
                (
                    "members",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"permissions": [("view_budget", "Can view budget")]},
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=250, unique=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("default_price", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_net",
                    models.BooleanField(default=True, verbose_name="Prices are net"),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, help_text="Is the purchase paid?"
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=255)),
                (
                    "payer",
                    models.CharField(
                        blank=True,
                        help_text="Person who paid the invoice",
                        max_length=255,
                    ),
                ),
                ("ordered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.Vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.Event",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.Team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REQ", "Requested"),
                            ("APP", "Approved"),
                            ("REA", "Ready for pick-up"),
                            ("COM", "Completed"),
                        ],
                        default="REQ",
                        max_length=30,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=1000)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="If you have more specific requirements, please add them as a comment.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.Product",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("request_order", "Can request a order"),
                    ("approve_order", "Can approve a order"),
                    ("receive_order", "Can receive order"),
                    ("complete_order", "Can complete order"),
                    ("export_csv", "Can export all orders as CSV"),
                    ("view_order_all_teams", "Can view orders for all teams"),
                    ("add_order_all_teams", "Can add orders for all teams"),
                    ("change_order_all_teams", "Can change orders for all teams"),
                    ("delete_order_all_teams", "Can delete orders for all teams"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Stockpile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("unit_price", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orders.Product"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.Purchase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pillage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.Order"
                    ),
                ),
                (
                    "stockpile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.Stockpile",
                    ),
                ),
            ],
        ),
    ]
