# Generated by Django 2.2.6 on 2019-11-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="pieces", max_length=20),
        ),
    ]
