# Generated by Django 3.0.7 on 2020-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpile",
            name="tax",
            field=models.FloatField(
                default=1.19,
                help_text="The tax rate as a factor of the net price",
                verbose_name="Tax rate",
            ),
            preserve_default=False,
        ),
    ]
