# Generated by Django 3.0.7 on 2020-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_stockpile_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockpile",
            name="unit_price",
            field=models.PositiveIntegerField(
                help_text="Price per unit in 1/10th of a cent"
            ),
        ),
    ]
