# Generated by Django 3.0.7 on 2020-07-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_product_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="vendor", options={"ordering": ["name"]},),
    ]
