# Generated by Django 3.0.7 on 2020-07-18 11:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_costitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="ordered_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="paid_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
