# Generated by Django 3.0.7 on 2020-07-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_purchase_ordered_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="rebate",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Rebate in %", max_digits=3
            ),
        ),
    ]
