# Generated by Django 2.2.6 on 2019-12-01 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_auto_20191201_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order", name="url", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.Product",
            ),
        ),
    ]
