# Generated by Django 3.0.7 on 2020-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_purchase_rebate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="rebate",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Rebate in %", max_digits=5
            ),
        ),
    ]
