# Generated by Django 2.2.6 on 2019-12-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_auto_20191201_2055"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="wish", new_name="product_suggestion",
        ),
    ]
