# Generated by Django 3.0.7 on 2020-07-18 13:21

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_auto_20200718_1252"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": [django.db.models.functions.text.Upper("name")],
                "permissions": [("view_budget", "Can view budget")],
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
    ]
