# Generated by Django 2.2.6 on 2019-12-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_auto_20191202_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
