# Generated by Django 3.0.7 on 2020-07-19 16:42

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_auto_20200718_1321"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockpile",
            options={
                "ordering": [django.db.models.functions.text.Upper("product__name")]
            },
        ),
    ]
