# Generated by Django 2.2.8 on 2019-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_auto_20191203_2327"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team", options={"permissions": [("view_budget", "Can view budget")]},
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
