# Generated by Django 3.0.7 on 2020-07-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_stockpile_order_by_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("export_csv", "Can export all orders as CSV")]},
        ),
        migrations.RemoveField(model_name="order", name="state",),
    ]
