# Generated by Django 3.0.7 on 2020-07-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_remove_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase", options={"ordering": ["ordered_at"]},
        ),
    ]
