# Generated by Django 3.0.7 on 2020-08-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_purchase_order_by_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockpile",
            name="tax",
            field=models.DecimalField(
                decimal_places=4,
                help_text="The tax rate as a factor of the net price",
                max_digits=19,
                verbose_name="Tax rate",
            ),
        ),
    ]
