# Generated by Django 2.2.8 on 2019-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_auto_20191208_1753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("REQ", "Requested"),
                    ("APP", "Approved"),
                    ("REA", "Ready for pick-up"),
                    ("COM", "Completed"),
                ],
                default="REQ",
                max_length=30,
            ),
        ),
    ]
