# Generated by Django 2.2.8 on 2019-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_auto_20191219_2037"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
