# Generated by Django 2.2.8 on 2020-01-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_order_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [
                    ("request_order", "Can request a order"),
                    ("approve_order", "Can approve a order"),
                    ("receive_order", "Can receive order"),
                    ("complete_order", "Can compelete order"),
                    ("export_csv", "Can export all orders as CSV"),
                ]
            },
        ),
    ]
