# Generated by Django 2.2.10 on 2020-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_auto_20200131_1936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="is_net",
            field=models.BooleanField(
                default=True,
                verbose_name="Do items of this purchase show the net sum (and not the gross sum)?",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="paid",
            field=models.BooleanField(
                default=False, verbose_name="Is the purchase paid?"
            ),
        ),
    ]
