# Generated by Django 2.2.12 on 2020-04-21 20:04

import django.db.models.deletion
from django.db import migrations, models


def set_product_name(apps, schema_editor):
    """
    Sets the product_name to product.name

    We can’t import the Order model as it is newer than what we need:
    it already has the field product with to_field="name" set
    """

    order_model = apps.get_model("orders", "order")
    for order in order_model.objects.all():
        order.product_by_name = order.product
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_require_product"),
    ]

    operations = [
        # Add a new field product_by_name that is configured as we want the product field to look in the end
        migrations.AddField(
            model_name="order",
            name="product_by_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.Product",
                to_field="name",
            ),
        ),
        # Set product_by_name for all orders
        migrations.RunPython(set_product_name, elidable=True),
        # Remove the product field
        migrations.RemoveField(model_name="order", name="product"),
        # Rename product_by_name to product
        migrations.RenameField(
            model_name="order", old_name="product_by_name", new_name="product"
        ),
    ]
