# Generated by Django 2.2.12 on 2020-04-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_product_pk_to_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="url",),
    ]
