# Generated by Django 2.2.12 on 2020-04-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_remove_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="good",),
        migrations.DeleteModel(name="Good",),
    ]
