# Generated by Django 2.2.12 on 2020-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_remove_good"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
