# Generated by Django 3.0.5 on 2020-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_unit_price_allow_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
