# Generated by Django 3.0.5 on 2020-04-24 14:13

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0035_product_unit_not_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0000"))
                ],
            ),
        ),
    ]
