# Generated by Django 3.0.5 on 2020-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0039_remove_order_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="default_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
