# Generated by Django 3.0.5 on 2020-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_auto_20200424_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
