# Generated by Django 3.0.7 on 2020-06-14 19:36

import django.db.models.deletion
from django.db import migrations, models


def migrate_from_product_name_to_id(apps, schema_editor):
    """
    If the order has a product_suggestion, we create a new product with the same name and set it as product.
    Then, we remove the product_suggestion field
    """

    order_model = apps.get_model("orders", "order")
    product_model = apps.get_model("orders", "product")

    for order in order_model.objects.all():
        product = product_model.objects.get(name=order.product.name)
        order.product_new = product
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_product_unit_allow_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpile",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.Purchase",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.Product",
            ),
        ),
        migrations.RunPython(migrate_from_product_name_to_id, elidable=True),
        migrations.RemoveField(model_name="order", name="product",),
        migrations.RenameField(
            model_name="order", old_name="product_new", new_name="product",
        ),
        migrations.AlterField(
            model_name="stockpile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.Product"
            ),
        ),
    ]
