# Generated by Django 3.0.7 on 2020-06-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0041_product_unit_allow_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpile",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.Purchase",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.Product",
            ),
        ),
        migrations.AlterField(
            model_name="stockpile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.Product"
            ),
        ),
    ]
