# Generated by Django 3.0.7 on 2020-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0042_auto_20200614_1936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="is_net",
            field=models.BooleanField(default=True, verbose_name="Prices are net"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="paid",
            field=models.BooleanField(default=False, help_text="Is the purchase paid?"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payer",
            field=models.CharField(
                blank=True, help_text="Person who paid the invoice", max_length=255
            ),
        ),
    ]
