# Generated by Django 3.0.7 on 2020-06-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0044_auto_20200616_2138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                help_text="If you have more specific requirements, please add them as a comment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.Product",
            ),
        ),
    ]
