# Generated by Django 3.0.7 on 2020-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_purchase_order_by_date"),
        ("accounts", "0002_transactions_fix_sign"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="purchase",),
        migrations.AddField(
            model_name="transaction",
            name="purchase",
            field=models.ManyToManyField(blank=True, to="orders.Purchase"),
        ),
    ]
