# Generated by Django 3.0.7 on 2020-07-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_transaction_purchase_manytomany"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="purchase", new_name="purchases",
        ),
    ]
